### ISSUE TITLE
Bioconductor Train-the-Trainers

### ISSUE THREAD

**Issue by smcclatchy** [smcclatchy/studyGroup#73]
Bioconductor Train-the-Trainers with Dr. Martin Morgan of Bioconductor / SUNY-Buffalo
To develop talent in teaching R and BioConductor packages for RNA-seq and single-cell analysis, and variant annotation and calling. This one-day train-the-trainers workshop will be held on Thurs Sep 27 in Bar Harbor. Participants will be expected to teach in R and sequencing workshops following the training. Those who have been through Carpentry instructor training will be prioritized for admission.

**Comment by aplancha** [comment]
Hi Sue - would you mind removing my email from the listserv? I’m not at JAX anymore.

Greetings from steamy North Carolina.

Tony

**Comment by wflynny** [comment]
@aplancha You may be getting the notifications because you are "Watching" the repository.  If you "Unwatch" the repo, you shouldn't receive any notifications unless specifically mentioned using `@aplancha`.

**Comment by omsai** [comment]
@smcclatchy I've been interested in Carpentry materials for Bioconductor, and was wondering if you knew what the strategy was with Dr. Martin Morgan and your Train-the-trainers workshop?  Are Bioconductor materials for the Carpentries being planned or developed?

Prof. Naupaka Zimmerman mentioned on the maintainers-genomics mailing list that unpublished R Genomics lessons are being overhauled, but I don't know whether any of that involves a heavy Bioconductor workflow as opposted to something less like teaching more of core R and making plots from command-line tool data - [the email discussion is here](https://carpentries.topicbox.com/groups/maintainers-genomics/Tc750ab2a8aaf4aa1-Meee4d465ba3bdce088ce3f6c).

Looking upstream, I see Martin and others have been working on a [new set of workshop materials](https://github.com/Bioconductor/BiocWorkshops) since at least this May and wonder what the vision is of developing that alongside Carpentry teaching.  When I talked to Martin at the Bioconductor conference last year, he was aware of the Carpentries but not involved with workshops; he mentioned teaching his materials at Rosewill Park.  I also talked to Prof. Vincent Carey this May who co-organizes the Boston R Bioconductor meetups who was familiar with the carpentries and supports moving to Carpentry style teaching of Bioconductor materials.  So this is all to say it's exciting to hear the two groups coming together.
